name: Build and deploy

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install
        run: |
          npm ci
          npm run build
      - name: Run tests
        run: npm test
  deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          script: |
            tmux kill-session -t service_tmux_session
            git clone https://github.com/dualis-scanner/dualis-scanner.service.git
            cd dualis-scanner.service
            git pull
            tmux new -s service_tmux_session -d
            tmux send-keys -t service_tmux_session npm ci ENTER
            tmux send-keys -t service_tmux_session npm run build ENTER
            tmux send-keys -t service_tmux_session npm run start ENTER
